### ISSUE TITLE
Using this in Outlook Desktop or Outlook.com

### ISSUE THREAD

**Issue by lewisje** [mganss/EmojiAddIn#1]
How is that done?

**Comment by mganss** [comment]
Go the [add-in's page in the Office Store](https://store.office.com/de-de/app.aspx?assetid=WA104380335) and click the Add button. Once you have added the add-in to your online account it will automatically be available from within Outlook Desktop also. If Outlook Desktop is open when you add the add-in online, you need to close and re-open Outlook Desktop for the add-in to become available there.

**Comment by zommuter** [comment]
You should mention this in the README.
