### ISSUE TITLE
Icons doesn't open

### ISSUE THREAD

**Issue by eliadvertman** [mganss/EmojiAddIn#10]

**Comment by eliadvertman** [comment]
When I try to open emoji category, 
the icons that should appear below that do not appear.
I checked and no errors at the console log. Any advice?

**Comment by mganss** [comment]
- Are you using Thunderbird or Outlook?
- Can you provide a screenshot?

**Comment by eliadvertman** [comment]
Using Outlook.
![3a5346f7-b1d3-4bb0-ae77-345968c3484d](https://user-images.githubusercontent.com/7227593/29585138-c0b7dc42-878e-11e7-8d11-8bc56b022840.jpg)

when i open the Taskpane html the taskpane.scss is loaded and it looks better, but from outlook even that doesn't work.

But the most import thing is that the category doesn't open up the emojis.

**Comment by mganss** [comment]
It looks like something's preventing some files from being loaded. Unfortunately, to my knowledge it's not possible to debug problems with add-ins in Outlook desktop so we'll have to do trial-and-error.
- Do you have the latest version of IE? (IE is being used by Outlook to render the add-in)
- Does everything work ok in Outlook Web using IE?
- When you load https://mganss.github.io/EmojiAddIn/AddInCompose/TaskPane/TaskPane.html in IE, does it look the same?
- If so, press F12 in IE, go to the network tab, do a reload and check if there are any errors. Also, check the console output of IE.

**Comment by fatman45** [comment]
Hi - I have the same issue in Outlook 2016 desktop client. I loaded the link into IE11 and it looks the same as in Outlook. F12 shows no console errors, Network shows one 404 error.
`Name	Protocol	Method	Result	Content type	Received	Time	Initiator
https://telemetryservice.firstpartyapps.oaspapps.com/telemetryservice/telemetryproxy.html	HTTPS	GET	404	text/html	1.22 KB	85.87 ms	document`
Is this the problem? It actually was working correctly all last week. The best it ever has. Previously, I could select emojis to insert but I couldn't see them, only the hover text. Which made it very difficult to find the one I wanted!

![image](https://user-images.githubusercontent.com/1221172/39413529-63261668-4be0-11e8-9e1f-8d05f974013e.png)

**Comment by fatman45** [comment]
I tried your suggestions. Still no joy. The only error I see is the 404 error mentioned above.

**Comment by mganss** [comment]
Please also try the suggestions at #16 specifically clearing the IE cache.
