### ISSUE TITLE
Not working: Emojis Add-in for Microsoft Outlook 2016 MSO 64-bit

### ISSUE THREAD

**Issue by mescherzinger** [mganss/EmojiAddIn#11]
I have just installed the Emojis Add-in for Microsoft Outlook 2016 MSO 64-bit (desktop). (Emojis version 1.0.0.3 Created by: UpdateStar GmbH)

After I launch the app in a new email, I should be able to select a category of emojis, but all the categories are grayed out; when I try to click on a category (i.e.,  Smileys & People), it doesn't show me any emojis to choose from.

What can I do to be able to use this add-in?

Thank you, 

Mindy Scherzinger
mescherzinger@graniteschools.org

![emojis add-in not working](https://user-images.githubusercontent.com/31971341/30455493-6284cad2-995d-11e7-84ad-b439527c336c.PNG)

**Comment by mganss** [comment]
Does it work in Outlook Web using IE on the same machine?

**Comment by mescherzinger** [comment]
Yes, it does. [??]   However, I don't normally use OWA because it doesn't seem to have all the functionality of the desktop version.  [??]


________________________________

**Comment by mganss** [comment]
Unfortunately, it's notoriously difficult to debug add-ins in Outlook desktop. Please try the suggestions in #3.

**Comment by mescherzinger** [comment]
Thank you for taking the time to offer the suggestion; it looks like it’s going to take more time to figure out than I want to spend on it, so I think I’ll just delete the add-in.

Thanks,
Mindy Scherzinger
School Climate Grant Secretary
Research & Evaluation Department
Granite School District
385-646-2185
mescherzinger@graniteschools.org<mailto:mescherzinger@graniteschools.org>
