### ISSUE TITLE
Not inserting correct emoji selected

### ISSUE THREAD

**Issue by marisa772** [mganss/EmojiAddIn#15]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Microsoft Outlook 2016 MLS (16.0.9029.2106) 32-bit

### Expected behavior
Select an emoji, then add to email.

### Actual behavior
Not inserting the emoji that I selected - inserting other emoji instead

### Steps to reproduce the behavior
Open an email or reply to an email in Outlook, 
put cursor in body of email
open Emoji add on
Select emoji such as 
![image](https://user-images.githubusercontent.com/37549997/37608751-be79b9f0-2b71-11e8-8f3c-66f2d26a8381.png) but when it adds to email it comes out as 
![image](https://user-images.githubusercontent.com/37549997/37608778-cda2fab8-2b71-11e8-988f-8a220227b3cd.png)

When in the add on interface, if you hover over many of the emoji, you will see their alternative/hover text does not match the icon selected, and the one inserted matches this hover text. It almost seems as if the previews are cached and/or not refreshing.
![image](https://user-images.githubusercontent.com/37549997/37608883-0db687b4-2b72-11e8-8804-d87154a7cbf7.png)

**Comment by mganss** [comment]
Sorry, I can't repro. In your screenshot, a few images are not in the correct position, e.g. the first (top left) icon in this category should be red heart. The tooltips seem to be correct because where "heavy check mark" is in your screenshot there should be "eight-spoked asterisk".

Please do a reload by right-clicking in the sidebar and selecting "Reload" (also try pressing shift while selecting "Reload"). If that doesn't help, please try re-installing the add-in.

**Comment by marisa772** [comment]
Hi Michael,

I have tried the reload function and nothing changed. I also uninstalled and re-installed the add-on before I even opened a bug ticket.
Any other ideas? :( I love the add-on so I hope I can get it to work properly again.

Marisa

**Comment by mganss** [comment]
How does it look in Outlook Web (using IE)? Are you using the latest version of IE?

**Comment by mganss** [comment]
Do you see the Unicode 10 emojis such as T-Rex or Zebra (at the bottom of the animals category)?

**Comment by marisa772** [comment]
Yes I see the T-Rex and the Zebra
[cid:image001.png@01D3C02E.29A23040]

**Comment by marisa772** [comment]
I am seeing the same issues in IE using the Outlook web app:

[cid:image001.png@01D3C02E.94469A80]

Marisa

**Comment by marisa772** [comment]
Forgot to mention I’m using IE 11 (version 11.0.9600.18952)

**Comment by mganss** [comment]
I still can't repro in IE. But now we can debug. Please open the developer tools in IE by pressing F12:

- Go to the tab "Console". Are there any error messages?
- Click on the arrow in the top left corner (below F12) then click on one of the emojis that are in the wrong place. What does the corresponding source line say? Should be something like
```HTML
<span title="eight-spoked asterisk" class="emojione emojione-32-symbols _2733 symbols" id="2733" data-unicode="2733"></span>
```
- From this location in the source scroll up to the head of the iframe. There should be a line that says:
```HTML
<link href="https://cdn.jsdelivr.net/emojione/assets/3.1.1/sprites/emojione-sprite-32.min.css" rel="stylesheet">
```

**Comment by marisa772** [comment]
Hi Michael,

I don’t know if you did anything but now the icons are appearing properly both in my desktop version of Outlook AND in the IE web app! [😁]  I followed your instructions below and received no errors and everything was what it should be so I am assuming that it’s fixed now…?! Yay!

Marisa
