### ISSUE TITLE
Some emojis not displaying

### ISSUE THREAD

**Issue by biohazardxxx** [mganss/EmojiAddIn#16]
### Application and version where the issue occurs:
 Outlook Desktop 2016 & Outlook Web

![image](https://user-images.githubusercontent.com/1370362/38085670-b9c46c56-3351-11e8-8500-f5f8d619adce.png)

At other cotegories others icons are missing and at a few categories all are displayed ok.

Best regards

**Comment by biohazardxxx** [comment]
I am using Chrome. Ctrl+F5 did not help

**Comment by mganss** [comment]
Does it look the same in IE?

**Comment by biohazardxxx** [comment]
Finally I had a chance to test. In IE and FIrefox it looks ok.
Only Chrome and Outlook it self don't work. Any clue?

**Comment by mganss** [comment]
Bizarre. Outlook Desktop uses IE so it would be natural to expect the behavior to be identical between these two. But Chrome? Do the emoji at https://www.emojicopy.com/ display correctly in Chrome?

**Comment by mrzap000** [comment]
Hi, not sure if that is relevant but had the same issue in outlook desktop (some icons not displayed even reloading). I cleared Internext Explorer's cache and all icons within the outlook 365 addin were displayed again.

**Comment by bolliggit** [comment]
Some more detail here: It seems IE11 is getting confused regarding the pixel resolution, and applying mis-matching styles in some instances. See screenshot below, where it is using the @2x image position, but the @1x image.
![emoji screenshot-css](https://user-images.githubusercontent.com/38873623/39794958-a5124a28-537f-11e8-969b-d3066ea76081.png)

The rest of this is speculation. I know that Windows has some issues understanding screen pixel density where multiple screens are in use (I have two external screens attached to a laptop), see https://support.microsoft.com/en-au/help/3025083/windows-scaling-issues-for-high-dpi-devices, so this might have something to do with why the CSS is failing, and could explain why the issue persists across browsers. As a fix, you could consider supplying @2x emoji to all users, regardless of the resolution, and simply scale them to fit.

**Comment by biohazardxxx** [comment]
Interesting, I also have two screens attached to laptop. Also what I observed is that some days some icons work fine and on other days they don't. Today since a long time even all seem to be displayed!

**Comment by mganss** [comment]
OK, now using 2x sprites always. Tweaked the CSS and now serving from GitHub instead of the EmojiOne CDN. Unfortunately, this means the images look worse on non-high-res monitors.

**Comment by mfantone** [comment]
Apologies for the confusion. I was simply looking for a final answer to the user's question at the top of this thread about why the emojis don't appear. I followed the process and downloaded the zip file from your site. So now the zip is sitting on my desktop. It contains all of the emojis (they look great!) But I can't seem to get them into Outlook. I'm on Windows 10, using Outlook 2016 and Chrome as my default browser
![desktop](https://user-images.githubusercontent.com/39503226/40377048-bfeae3c6-5da4-11e8-986d-ce349827ee53.jpg)

**Comment by mganss** [comment]
@mfantone Which download do you mean? You shouldn't have to download anything, just install the add-in through the Office Store.

**Comment by mganss** [comment]
Accidentally closed 😊

**Comment by mfantone** [comment]
I understand I shouldn't have had to download anything but since the emojis weren't showing up, I clicked the only thing with an active link which was the one for Emoji One. I clearly have added the add-in since you can see the Emoji icon on the toolbar ribbon. I'm just not getting the emojis to appear where they should be.
![emojis](https://user-images.githubusercontent.com/39503226/40439913-3e12e376-5e71-11e8-81a2-dcd6e41e06c2.jpg)

**Comment by mganss** [comment]
@mfantone What happens when you click on one of the category icons at the top? Have you tried all of the suggestions here? Does it behave identically in Chrome and IE?

**Comment by biohazardxxx** [comment]
just a note for me the emjos display fine since my last message. So initial issue is fixed ;-)

**Comment by mfantone** [comment]
All of the category icons remain grayed out when I roll over them so there's nothing to click open. I don't have IE installed and run Outlook 2016 through Microsoft 365. Don't know what else I can share.

**Comment by mganss** [comment]
@mfantone At #18 you reported that the issue occurs in Chrome also?

**Comment by mfantone** [comment]
Chrome is all I use
