### ISSUE TITLE
Resolution for #16?

### ISSUE THREAD

**Issue by mfantone** [mganss/EmojiAddIn#18]
Wondering if a solution was found for the topic in #16. I run Chrome and have the same issue on my desktop.

I'm also wondering about the EmojiOne_3.1.1_128x128_png zip file with all of the emojis that were part of the download from the site. Right now they are sitting on my desktop wondering where they are supposed to go.

**Comment by mganss** [comment]
Please post comments for #16 at #16. Which download do you mean (please answer at #16)?
