### ISSUE TITLE
Emojis for Outlook Desktop 2016

### ISSUE THREAD

**Issue by abangemann** [mganss/EmojiAddIn#19]
Emojis, Outlook Desktop 2016

Is there a chance to get "Emojis" work on Outlook **Desktop** 2016?

Regards, Andreas.

**Comment by mganss** [comment]
Yes, it works on Outlook Desktop, too. Once you have installed the add-in through Outlook Web, it shows automatically in Outlook Desktop.

**Comment by abangemann** [comment]
No, it does not!

- I klicked "Get it" at appsource.microsoft.com.
- I aggreed to the Terms
- then there was a message "Taking yout to Office 365 to complete this process"
- I had to sign in to Microsoft Offie 365
- I came to the Options > AddIns site of Outlook Web

**Comment by mganss** [comment]
The add-in should show up in the "New email" window. Also, it works only for the account you have added the add-in to, not other accounts (e.g. IMAP accounts) you might have added to Outlook Desktop.
