### ISSUE TITLE
No release to download

### ISSUE THREAD

**Issue by zommuter** [mganss/EmojiAddIn#2]
While #1 mentions the Outlook add-in can be obtained [here](https://store.office.com/de-de/app.aspx?assetid=WA104380335), without a Microsoft account it cannot be obtained. Offering an alternate release (as described [here](https://help.github.com/articles/creating-releases/))to download directly here would therefore be most helpful.

**Comment by mganss** [comment]
I've added sections describing the installation process for both Outlook and Thunderbird to the README. For Outlook, you will always need a Microsoft account as there is no way to install an add-in other than through Outlook online. For Thunderbird, you can download and install the xpi from the add-on's detail page at Mozilla as described in the README.

**Comment by zommuter** [comment]
Our DMS has a simple installer exe for its add in, so add in installation without a Microsoft account is very possible. I just don't know whether it requires much additional work or not, a quick search yielded

* [Deploying an Office Solution by Using Windows Installer](https://msdn.microsoft.com/en-us/library/cc442767.aspx)
* [Deploying a Visual Studio 2010 Tools for Office Solution Using
Windows Installer](https://msdn.microsoft.com/en-us/library/ff937654.aspx)
* [Building and deploying an Outlook 2010 Add-in (part 2 of 2)](https://blogs.msdn.microsoft.com/mcsuksoldev/2010/10/01/building-and-deploying-an-outlook-2010-add-in-part-2-of-2/)

**Comment by mganss** [comment]
This project is not a VSTO add-in but rather an add-in based on the [Office JavaScript API](http://dev.office.com/docs/add-ins/overview/office-add-ins) (formerly known as "Apps for Office").

**Comment by zommuter** [comment]
I see - but how do you test it yourself? Always via Microsoft? What about [sideloading](https://dev.office.com/docs/add-ins/publish/publish)?

**Comment by mganss** [comment]
Yes, they call it sideloading but you still have to [upload the manifest](https://dev.office.com/docs/add-ins/testing/sideload-outlook-add-ins-for-testing) file through Outlook online.

**Comment by zommuter** [comment]
That's unfortunate then... Thanks for the feedback though
