### ISSUE TITLE
image storage site

### ISSUE THREAD

**Issue by joaoavilars** [mganss/EmojiAddIn#21]
I tried to use the add-in in my Outlook client on my desktop, but when I try to select one of the icons the image does not appear.
my internet is made available by a proxy server, I will probably have to release the storage site of the images by some bypass rule.
What would be the site?

English by google translate ...

**Comment by mganss** [comment]
You need to allow the following sites:

- ajax.aspnetcdn.com (for jQuery)
- appsforoffice.microsoft.com (Office add-in JavaScript)
- mganss.github.io (images in the task pane)
- cdn.jsdelivr.net (emoji images added to emails)
