### ISSUE TITLE
Enigmail icons gone after installing Emoji

### ISSUE THREAD

**Issue by franzs** [mganss/EmojiAddIn#22]
### Application and version where the issue occurs

Thunderbird 60.2.1 with Enigmail 2.0.8

### Expected behavior

Enigmail's icons for signing and encrypting should appear as they did before installing Emoji:

![tb_emoji_expected](https://user-images.githubusercontent.com/425188/47635182-6bf8bf80-db54-11e8-91f8-bc43f8842e31.png)

### Actual behavior

Enigmail's icons are gone. Instead the S/MIME dropdown is shown:

![tb_emoji](https://user-images.githubusercontent.com/425188/47635073-fb51a300-db53-11e8-8fc4-e6c415ed9b4b.png)

### Steps to reproduce the behavior

Start with Thunderbird 60.2.1 and Enigmail 2.0.8. Install version 1.5.6 of Emoji addon.

**Comment by mganss** [comment]
I still don't know the root cause of this problem and whether it's a problem in the extension, Thunderbird itself, or Enigmail, but I've made a hacky fix that seems to solve the issue 🤷‍♂️

**Comment by franzs** [comment]
Works for me like a charm, now. Thanks alot!
