### ISSUE TITLE
Add-in Error #23

### ISSUE THREAD

**Issue by MartinArundel** [mganss/EmojiAddIn#23]

**Comment by MartinArundel** [comment]
16.0.4738.1000 office version. Works fine online just the local outlook doesn't work
Appears to be unique to this one user. They have admin rights over the machine

**Comment by mganss** [comment]
Please see possible solutions [here](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting). If that doesn't help and you want to dig deeper, please try a method described [here](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/test-debug-office-add-ins) and report your findings here.

**Comment by mganss** [comment]
No feedback, closing.
