### ISSUE TITLE
Please add sidebar to the chat window

### ISSUE THREAD

**Issue by LaHaine** [mganss/EmojiAddIn#24]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Thunderbird 60.2.1 Ubuntu 18.04 x86_64
### Expected behavior
The sidebar isn't available when using the chat window of thunderbird.
### Actual behavior
The sidebar is in the email composer window only.
### Steps to reproduce the behavior
Add a chat window and type something.

**Comment by mganss** [comment]
Nice additional feature. I have no interest in it, though, so someone else needs to pick this one up. Feel free to submit a PR.

**Comment by RanTrycl** [comment]
+1 for this, would really love it. (I looked at Pull Requests but was not sure what to do there, sorry.)

**Comment by mganss** [comment]
Added in 1.68.4 (currently under review at Mozilla).

**Comment by RanTrycl** [comment]
What! Really? Gobsmacked ... thank you!
