### ISSUE TITLE
Cannot Access the Imoji Panel

### ISSUE THREAD

**Issue by UNDERPAIDBOOKKEEPER** [mganss/EmojiAddIn#25]
I first installed Emoji by Michael Ganss a few months ago and it worked perfectly.  Then, all of a sudden, the Emoji panel on the right was gone as well as the icon at the top which toggles it on or off.  I figured the easiest way to solve the problem would be to simply uninstall it and them reinstall it, which I did.  But still no Emoji panel or icon.  I have Thunderbird 60.3.3 and Emoji 1.5.8.  Be great if I could get it back.  Any ideas?

**Comment by mganss** [comment]
What does it say on the Add-ons manager tab? Click "Add-ons" in the menu then "Extensions" on the left side.

Also, if the Emoji button in the toolbar is not there, there's also the menu item in the "View" menu where you can toggle display of the emoji panel.

**Comment by mganss** [comment]
No feedback, closing.
