### ISSUE TITLE
Update for thunderbird 68

### ISSUE THREAD

**Issue by gene-git** [mganss/EmojiAddIn#27]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Thunderbird 68 (and 70)

### Expected behavior
Install and use

### Actual behavior
Cannot be installed - incompatible with TB 68+

### Steps to reproduce the behavior

Be great if this can be updated to work with the beta version, which is set to be the new released version.

**Comment by mganss** [comment]
Sorry for the late response 😳 Fixed in 1.6.68 (currently under review at AMO).

**Comment by mganss** [comment]
Review failed. Reopen 🙄

**Comment by mganss** [comment]
1.68.1 works with TB 68
