### ISSUE TITLE
Emoji 1.68.1 not working in Thunderbird Version 68.4.2. (32-bit)

### ISSUE THREAD

**Issue by cbfunk** [mganss/EmojiAddIn#28]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Thunderbird Version 68.4.2. (32-bit)

### Expected behavior
Sidebar with Emojis

### Actual behavior
No sidebar, not visible at all

### Steps to reproduce the behavior
remove & reinstall

![Screenshot 2020-01-31 12 44 21](https://user-images.githubusercontent.com/60508144/73536965-81c7f500-4427-11ea-9f84-5a58504a7704.png)

![Screenshot 2020-01-31 12 45 45](https://user-images.githubusercontent.com/60508144/73537009-a2904a80-4427-11ea-9cc2-58c9950dba00.png)

**Comment by mganss** [comment]
Have you checked Emoji in the View menu?

**Comment by cbfunk** [comment]
Thank you I hadn't tried that yet. 
Now the pane is here in the compose window but no Emojis.
See screen shot
![Screenshot 2020-01-31 14 04 34](https://user-images.githubusercontent.com/60508144/73541449-c2793b80-4432-11ea-91cc-db42859efb7a.png)

**Comment by mganss** [comment]
Please open the console and look for any errors related to the add-on there (Tools -> Developer Tools -> Developer Toolbox).

**Comment by cbfunk** [comment]
I did look, but no error message pertaining to the Emoji addon.

**Comment by mganss** [comment]
Please also click on the little window icon at the top right in the developer toolbox (next to the three dots) and select `chrome://emoji/content/emoji.html` (message compose window needs to be open). Are there any error messages?

Also click "Inspect" at the top left in developer console, expand the `<body>` element and see what's there. There should be several child elements that make up the UI of the add-on but from your screenshot it looks empty.

**Comment by cbfunk** [comment]
I did check, but I don't think there are any for the Emoji addon
![Screenshot 2020-02-04 09 51 39](https://user-images.githubusercontent.com/60508144/73728802-459cd900-4734-11ea-80a1-3e1b80db78d7.png)
![Screenshot 2020-02-04 09 52 20](https://user-images.githubusercontent.com/60508144/73728803-459cd900-4734-11ea-8556-1057ebe71a17.png)

**Comment by cbfunk** [comment]
chrome://emoji/content/emoji.html  is not in the window pop up
see screen shot

Inspect shows some emoji lines :)
see screenshot

![Screenshot 2020-02-04 16 35 04](https://user-images.githubusercontent.com/60508144/73759832-cd063e80-476c-11ea-9957-e267913308b3.png)
![Screenshot 2020-02-04 16 35 13](https://user-images.githubusercontent.com/60508144/73759833-cd9ed500-476c-11ea-871a-7f5e96634889.png)

**Comment by mganss** [comment]
Were these screenshots taken when the emoji sidebar was disabled? Try toggling the emoji sidebar (using the menu item and X button on the sidebar) several times and see if there are any messages in the console (select the message compose window before in the developer console from the top right menu). Do you see any changes to the vbox element with id emoji-box?

**Comment by cbfunk** [comment]
I think it was enabled.
With this screenshot it is.
Showing the error messages when toggling.

I don't understand this question:
"Do you see any changes to the vbox element with id emoji-box?"

I'm sorry but I'm a bit in over my head with this developer tool :)

![Screenshot 2020-02-04 18 07 02](https://user-images.githubusercontent.com/60508144/73768901-1d37cd80-477a-11ea-9653-348ad2fef61e.png)

**Comment by mganss** [comment]
I think I know what's going on. Here's how you can work around this problem:
- Add the Emoji toolbar button to the toolbar by right clicking on the empty area on the toolbar (to the right of the "Print" toolbar button in your screenshot) and selecting Customize from the menu
- Drag the Emoji toolbar button to the toolbar. On my TB the icon doesn't show in the preview so you'll have to drag the empty part above the "Emoji" label 🙄 
- Restart TB
- Toggle the Emoji sidebar

**Comment by mganss** [comment]
Fixed in 1.68.2

**Comment by cbfunk** [comment]
omg, you're a genius !!! It's working !!! Thank you !!! Vielen Dank nach Berlin aus Wien :)
