### ISSUE TITLE
Unable to access website to find out how to reverse HTML emails to insert Unicode.

### ISSUE THREAD

**Issue by sjshaffer** [mganss/EmojiAddIn#29]

**Comment by sjshaffer** [comment]
I'm receiving the following from https://updatestar.com/  (http:// redirects to https://)
Error code: SSL_ERROR_ACCESS_DENIED_ALERT

**Comment by mganss** [comment]
Which link do you click before the error occurs?

You can insert a Unicode emoji into an HTML message by holding the Shift key while clicking the desired emoji.

**Comment by mganss** [comment]
No feedback, closing.
