### ISSUE TITLE
emoji 

### ISSUE THREAD

**Issue by griffshort** [mganss/EmojiAddIn#3]
i see the emoji button in my "message" menu bar, but it is greyed out and doesn't function.  

![emoji outlook](https://cloud.githubusercontent.com/assets/22621581/19083985/9256a63a-8a32-11e6-9955-59743c9bde2c.JPG)

**Comment by mganss** [comment]
Does it work in Outlook Web?
[Here](http://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_win10/add-ins-greyed-out-in-outlook-2016-win-message/30f052cc-b368-404b-a23c-5a20663e2622)'s a discussion that suggests it might have to do with other add-ins. Do you have other add-ins? If so, please try and disable them to see if this has any impact.

**Comment by griffshort** [comment]
It works in the web.  The only other add-ins I have are the default ones and one i downloaded that was a language translator.  I disabled all of them and it works now.  I will go back and turn them on one at a time to see which one is causing a conflict and let you know.

Thanks,



Griff Short
Engineering Manager, TSG
[TSG Logo]
229.944.2901<tel:229.944.2901> (Direct)
229.815.1217<tel:229.815.1217> (Mobile)
gshort@usa-tsg.com<mailto:gshort@usa-tsg.com>
www.usa-tsg.com<http://www.usa-tsg.com>
Sent from my Verizon Wireless 4G LTE smartphone
-------- Original message --------

**Comment by BetsyV** [comment]
The emojis do work in the web version of outlook but not my desktop version (Outlook 2013). It is grayed out, and I don't have ANY other add-ins. I have uninstalled it and tried reinstalling, but that didn't work. Do you have any suggestions?

**Comment by mganss** [comment]
In Windows Event Viewer, click the arrow to the left of "Applications and Services Logs", then click on "Microsoft Office Alerts". Then check if there is an event in the list that's related to the Emojis add-in. I have only Information-type events like this:

```
Activated App
Id=19d7837e-b9fc-4726-98ef-aaab8507fed1, DisplayName=Emojis, Provider=UpdateStar GmbH, StoreType=Exchange, StoreId=A545E4870E795B43A4FBA8AC1946B013
P1: Apps for Office
P2: 16.0.7927.1020
P3: 
P4: 
```

My hope is that in the case where the add-in is not properly activated there will be other types of events that indicate the cause of the problem.

**Comment by BetsyV** [comment]
I did find the event, but I am not sure what I am looking for to indicate a problem.
Log Name:      OAlerts
Source:        Microsoft Office 15 Alerts
Date:          4/26/2017 12:31:25 PM
Event ID:      300
Task Category: None
Level:         Information
Keywords:      Classic
User:          LUSD\villalpando.elizabet
Computer:      VMS-RB5-01.lusd.org
Description:
Activated App
Id=19d7837e-b9fc-4726-98ef-aaab8507fed1, DisplayName=Emojis, Provider=UpdateStar GmbH, StoreType=Exchange, StoreId=847C3065979A9446BFD0909BD2CA973D
P1: Apps for Office
P2: 15.0.4919.1001
P3: 
P4: 

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft Office 15 Alerts" />
    <EventID Qualifiers="0">300</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-04-26T19:31:25.000000000Z" />
    <EventRecordID>329</EventRecordID>
    <Channel>OAlerts</Channel>
    <Computer>VMS-RB5-01.lusd.org</Computer>
    <Security UserID="S-1-5-21-1158139434-3477731541-1622020533-2748" />
  </System>
  <EventData>
    <Data>Activated App
</Data>
    <Data>Id=19d7837e-b9fc-4726-98ef-aaab8507fed1, DisplayName=Emojis, Provider=UpdateStar GmbH, StoreType=Exchange, StoreId=847C3065979A9446BFD0909BD2CA973D
</Data>
    <Data>Apps for Office
</Data>
    <Data>15.0.4919.1001
</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by mganss** [comment]
Are there any other events with "Emojis" in the text on the General tab other than the "Activated App" events?

**Comment by BetsyV** [comment]
No. I have turned the app off and I have uninstalled and reinstalled, but the only messages I see are Activated App.

**Comment by mganss** [comment]
I have no idea how to diagnose this issue. I have [asked at StackOverflow](https://stackoverflow.com/questions/43853641/how-to-debug-office-add-in-activation-issues) what debugging options there are.

**Comment by BetsyV** [comment]
Thank you

**Comment by mganss** [comment]
The discussion at StackOverflow turned up the following page: https://dev.office.com/docs/add-ins/outlook/troubleshoot-outlook-add-in-activation
