### ISSUE TITLE
Red heart emoji appears in black + preferences

### ISSUE THREAD

**Issue by marcoagpinto** [mganss/EmojiAddIn#30]
Hello!

I have been inserting the emojis in HTML e-mails pressing the shift key so that it places an image instead of using remote content (which is annoying).

Could a setting be added to insert always as image in HTML e-mails?

Also, the red heart emoji inserts a black heart and the colour needs to be manually changed which means it is not an image but a character.

Thanks!

**Comment by mganss** [comment]
By default, images are inserted instead of characters in HTML emails. You can change the default in the add-on's settings (it's the only setting the add-on has :) If you enable this setting, the behavior is flipped, i.e. characters are inserted by default and images are inserted if you shift-click.

**Comment by marcoagpinto** [comment]
Ahhhh... thanks!

It worked!

What about the red heart emoji?

Thanks!

**Comment by mganss** [comment]
I fixed this in version 1.68.3 which is currently under review by Mozilla and should be available shortly.
