### ISSUE TITLE
Emoji 1.68.3 appears nowhere in Thunderbird 74 after installing

### ISSUE THREAD

**Issue by wilberfan** [mganss/EmojiAddIn#31]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Windows 10

### Expected behavior
A toolbar should appear to select emoji characters

### Actual behavior
No toolbars available anywhere

### Steps to reproduce the behavior
Install, restart Thunderbird.  Absolutely no addon toolbars available anywhere.

**Comment by mganss** [comment]
Try enabling the emoji sidebar from the View menu of the Write window. To add the emoji button to the toolbar follow these steps: https://github.com/mganss/EmojiAddIn/issues/28#issuecomment-582346299

**Comment by mganss** [comment]
No feedback, closing.
