### ISSUE TITLE
Emojis.

### ISSUE THREAD

**Issue by comima** [mganss/EmojiAddIn#33]
Hallo ! 
Ik ben nieuw en heb een probleem met de emojis... er is een update geweest naar TB versie 68 10 0. In de vorige versie had ik plezante en grote emojis die niet compatibel zijn met de nieuwe versie - mijn persoonlijk deuntje voor de inkomende mails heb ik kunnen oplossen. Een vriend heeft emojis op TB gezet maar ze zijn allemaal zo klein ... Kan ik misschien de vorige emojis ergens terug vinden ? 
Bedankt voor de moeite.
comima.

**Comment by mganss** [comment]
@comima I don't understand Dutch but as far as I can tell the Emojis appear smaller and look different than in the previous version? This may have to do with the preference setting that governs whether to insert Unicode characters or images. To check, open the add-on's settings and make sure the checkbox there is deselected.

If this doesn't solve your problem, please attach a screenshot here that shows the issue.

**Comment by comima** [comment]
I think my email to notifications@github.com never came to the right place ... this was my email : 
Ooooh Mister Ganss ... first of all thanks for your reaction and sorry for the language. I ' ll do my very best to continue in English.
Your Dutch is very good because what you wrote is all correct ! My new emojis are small and not nice ...
Included a screenshot from the settings of the TB add-ons. I hope it will be enough to help you further.
Thanks again for helping me out !
Kinds regards,
![Schermopname (51)](https://user-images.githubusercontent.com/68499830/88458786-bc6b9100-ce90-11ea-9ec5-60ce66d0cffc.png)

**Comment by mganss** [comment]
@comima To open the add-on settings, open the main menu, select Add-Ons and then (still in the menu) select Emoji. This will open the add-on settings in a separate tab. It seems you cannot access the add-on settings from the list of add-ons 🙄 

If that doesn't fix your issue, please attach a screenshot showing the compose window with the emoji sidebar open (and add a few emoji to the message).

**Comment by comima** [comment]
Thanks for your reaction and this is what I found ...
![Schermopname (53)](https://user-images.githubusercontent.com/68499830/88486952-b43f4e80-cf81-11ea-95b6-9a5ab4e5b993.png)
![Schermopname (54)](https://user-images.githubusercontent.com/68499830/88486953-b5707b80-cf81-11ea-9773-5fb1d8b25e36.png)

**Comment by mganss** [comment]
What happens if you Shift-click on an emoji in the sidebar (hold the Shift key while clicking on an emoji)?

The emoji in the message look strange because they obviously aren't the JoyPixels emoji images and neither do they look like the emoji Unicode characters built into Windows ([Microsoft Emoji](https://emojipedia.org/microsoft/)).

**Comment by comima** [comment]
Thanks mister ! It works ! Look at the screenhot !
I only have to remember to use the Shift ! 
Kind regards  and you made my day ! 
![Schermopname (56)](https://user-images.githubusercontent.com/68499830/88541470-16955f00-d015-11ea-9648-3b24515c108c.png)

**Comment by mganss** [comment]
You can change the default behavior through settings so you don't always have to press Shift: Open the main menu, then the submenu "Add-Ons" and in this submenu do not click on "Add-Ons" (this will lead you to the list of all add-ons as in your screenshot above) but instead click on "Emoji" (directly in the submenu below the heading "Add-On Options"). This will lead you the settings of Emoji in a new tab. There is only one setting for the Emoji add-on so this will be a mostly empty page. Uncheck the checkbox there (top left) and now you should be able to insert image emoji without the need to press Shift.

**Comment by comima** [comment]
I already tried and YESSSS ... I did it !
I would like to have just a very small part of your knowledge about TB ...
Thanks a lot !
