### ISSUE TITLE
Addon not working on Thunderbird 78

### ISSUE THREAD

**Issue by JackHack96** [mganss/EmojiAddIn#34]
I think @mganss already is aware about this bug, but I didn't seen any opened issue about Thunderbird 78.

### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Recently released Thunderbird 78

### Expected behavior
Addon working as previous versions

### Actual behavior
Addon not even loading, maybe caused by usage of legacy methods, as described here [https://developer.thunderbird.net/add-ons/updating/tb78](https://developer.thunderbird.net/add-ons/updating/tb78)

### Steps to reproduce the behavior
Update to Thunderbird 78, install the add-on manually and see that it's not working

**Comment by mganss** [comment]
@JackHack96 I'm aware and I plan to update but currently have very little time for this. EmojiAddIn is currently a "Legacy WebExtension" and needs to be converted to a MailExtension which seems to require significant rework because the overlay support was completely dropped.

**Comment by marcoagpinto** [comment]
Hello!

Any updates regarding TB 78 compatibility?

Next week will be released the last TB 68 update, then people will have to upgrade to 78.

I don't want to lose your add-on.

**Comment by mganss** [comment]
The next version is now under review at Mozilla.

**Comment by marcoagpinto** [comment]
Thank you!

**Comment by mganss** [comment]
Version 1.78.5 has been released.

**Comment by andrewwlo** [comment]
Thanks so much, I love this app and used it all the time in tb68 and have had a hard time living without it but I just downloaded it and am thrilled it's back. Just one question: why is there a warning that "this app needs full and unrestricted access to Thunderbird and your computer"?? That sounds so ominous?

**Comment by mganss** [comment]
@andrewwlo I have no idea. Then again, if you click on "Permissions" in the Add-ons Manager tab it says "This extension doesn’t require any permissions". Go figure. The only configured permission in the manifest.json is "storage", needed to save the preference setting.
