### ISSUE TITLE
Incompatibility with DKIM Verifier

### ISSUE THREAD

**Issue by Pradesh-GH** [mganss/EmojiAddIn#35]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Thunderbird 78.2.2 (64b)
### Expected behavior
DKIM Verifier should validate mails with Emoji.
### Actual behavior
But doesnt.
### Steps to reproduce the behavior
Sending mail with Emoji.
Reciving and verifing it with DKIM Verifier.
Getting Invalid (E-Mail was modified) message status.

Exemple with Emoji:
![DKIM with Emoji](https://user-images.githubusercontent.com/71440031/93468383-2b90bf00-f8ef-11ea-9c9c-c0091abdb9be.jpg)

Exemple without Emoji:
![DKIM without Emoji](https://user-images.githubusercontent.com/71440031/93468206-eb314100-f8ee-11ea-9152-d115b9206212.jpg)

**Comment by mganss** [comment]
This looks more like an issue within DKIM Verifier. What happens if you don't use the Emoji add-in to add the emoji character to your mail (e.g. instead just paste this: 😄 )?

**Comment by Pradesh-GH** [comment]
Exactly, I even tried with 8bits encoding characters and it's identical.
![DKIM with 8bits encoding](https://user-images.githubusercontent.com/71440031/93475264-b4f8bf00-f8f8-11ea-9eec-47ecd470169b.jpg)

So Emoji works perfectly😅

**Comment by mganss** [comment]
You might want to open an issue at https://github.com/lieser/dkim_verifier
