### ISSUE TITLE
Installs but doesn't appear

### ISSUE THREAD

**Issue by jailbird147** [mganss/EmojiAddIn#37]
Thunderbird 78.3.1(32bit)

Supposed to add an emoji panel to Thunderbird when I reply to an email

worked once then disappeared
![Annotation 2020-10-16 093621](https://user-images.githubusercontent.com/72966378/96226783-70ae1c80-0f93-11eb-8259-883449481dd5.png)
![Annotation 2020-10-16 093802](https://user-images.githubusercontent.com/72966378/96226793-7277e000-0f93-11eb-9f6d-9383ba04eae0.png)

reinstalled twice but doesn't work

**Comment by mganss** [comment]
Open the View menu and select the Emoji menu item.

**Comment by mganss** [comment]
No feedback, closing. Feel free to reopen if it still doesn't work.

**Comment by LAfricain** [comment]
Works for me. I had the same problem.
