### ISSUE TITLE
Not Able to Install or Use on Outlook 2012 (v1.0.0.3)

### ISSUE THREAD

**Issue by mani2jeff** [mganss/EmojiAddIn#38]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
App v1.0.0.3 on Outlook Desktop 2011/2012

### Expected behavior
Show emoji image in Outlook.

### Actual behavior
Using on Outlook 2011 inserts a frame but reports the image is not available.

### Steps to reproduce the behavior
Use the picker

**Comment by mganss** [comment]
Outlook Desktop below 2013 (Windows) or 2016 (macOS) are not supported. I'm surprised the add-on even installs. Have you installed through the Microsoft Store? Also I didn't even know Outlook 2012 was a thing (is this on macOS?)

**Comment by mani2jeff** [comment]
Michael. I was referring to the December 2020 Beta build. It has worked fine up until that point. Thanks

**Comment by mganss** [comment]
Ah ok. I can't repro using Version 2012 (Build 13524.20004), though.

**Comment by mani2jeff** [comment]
Michael. After not being able to install yesterday, I found it installed and working today. Not sure what was happening. Maybe it was something with the network. Sorry for the confusion.  Jeff
