### ISSUE TITLE
History page enhancement 

### ISSUE THREAD

**Issue by VERSEAU44** [mganss/EmojiAddIn#39]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Thunderbird 78.6.0

### Expected behavior
Could the history page display 2 parts :
1/ the last emojis used (to be able to configure the possible quantity)
2/ a selection of my favorite emojis (can also set their quantity) + special characters (ALL possible: É, ±, greek letters, etc)

**Comment by mganss** [comment]
Thanks for your suggestion. I'd rather keep the current behavior which is in line with how the history feature works in popular messengers. Note that the history page is ordered by frequency used, i.e. your favorite emojis should always be at the top.

**Comment by VERSEAU44** [comment]
I understand but ... I use a lot of Emojis and the quantity displayed in the History window is unfortunately not sufficient 😞

**Comment by mganss** [comment]
Currently it's 50 max. Would 100 suffice? Theoretically, there doesn't need to be a limit but I'd like to prevent cluttering of the history page.

**Comment by VERSEAU44** [comment]
Yes : GREAT 👍🏻

Do you know how I could add special characters and symbols because thunderbird's function is REALLY not user friendly (for accented letters but also being a scientist, I use greek letters a lot : create a new category ?)

THANKS for your help 🤞🏻

**Comment by mganss** [comment]
History size is 100 in 1.78.7.

**Comment by VERSEAU44** [comment]
GREAT 👍🏻

What about my question : do you know how I could add special characters and symbols via Emoji ? 
(Maybe by modifying a particular file ? Maybe by importing another emoji via https://www.joypixels.com ?)

Otherwise, Emoji could interpret in a new tab a csv file containing the display number, and its ISO code or Unicode compliant ...
(eg : https://www.toutimages.com/codes_caracteres.htm)

**Comment by mganss** [comment]
Sorry for the late response. I'm not sure I understand your question, though. Do you mean characters which are not part of the Unicode emoji standard? If so, this is definitely outside of the scope of this add-on. On Windows, you could try the built-in Character Map application.

**Comment by VERSEAU44** [comment]
You're right : I mean characters which are not part of the Unicode emoji standard ...

I was hoping that Emoji could keep ANY character I often use ...

I understand that this is not possible: too bad ...
