### ISSUE TITLE
Emojis are overlapping on a specific user's machine

### ISSUE THREAD

**Issue by bshaynes** [mganss/EmojiAddIn#4]
Hello!

I am reporting this on behalf of a user whose emojis in this add-in are large and overlapping. They look like this:

![emojis](https://cloud.githubusercontent.com/assets/25074356/21880610/e159605e-d86d-11e6-8e73-252ec3b38dde.png)

I have tried repairing Office, reinstalling it, and replacing the machine. I have attempted to remove the add-in, close out of Outlook, and load it as administrator but this still occurs. It is not a zoom issue, as zooming out or resizing the window still has some overlap. The emojis function technically, it is just very difficult to end up with the one that you want because you don't know which you're clicking on.

**Comment by mganss** [comment]
Thanks for reporting. Please let me know the versions/editions of IE, Windows, and Outlook. I have a hunch that this occurs because IE <= 9.

**Comment by bshaynes** [comment]
I believe it is Win7 Professional, Outlook 2013, and IE 11. I did some more work on it, and found that any using using that machine has the same issue, but that the user using a machine in a different location does not. To me, this is then a network connectivity issue. What do you think?

**Comment by mganss** [comment]
Can you try from Outlook Web in IE, then open F12 Developer Tools and check if there are any relevant errors in the Console tab?

**Comment by abeck21380** [comment]
I have this issue on Win 7 64 outlook 2016, it does not happen on my win 10 64 outlook 2016. the OWA side displays fine as well

**Comment by abeck21380** [comment]
IE mismatch on the 2 computers. Installing IE11 on culprit computer.

**Comment by mganss** [comment]
Did updating to IE 11 fix it? I've tested with Outlook Web on Windows 7 with IE 10 and it works. IE 9 and IE 8 bring up a completely different (old school) look in Outlook Web where add-ins are not shown at all.

**Comment by abeck21380** [comment]
Yes I had the exact same look of the Emoji screen that was listed in the original post, not only that, my store button in outlook did not display anything. Once I installed IE 11 everything displayed correctly.
