### ISSUE TITLE
TypeError: document.persist is not a function - overlay.js:96:26

### ISSUE THREAD

**Issue by jorgk3** [mganss/EmojiAddIn#40]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)

TB 78.6.1 (latest current), add-on version: 1.78.6.

This is shows every once in a while in the debug console:
TypeError: document.persist is not a function - overlay.js:96:26

persist was removed here: https://hg.mozilla.org/mozilla-central/rev/cf969e57bc7b

I suggest to remove the line since it doesn't work any more. Apparently there are no negative side effects.

**Comment by mganss** [comment]
Thanks for reporting this. Fixed in 1.78.7.
