### ISSUE TITLE
Emojis wont show in Editor, but at the Recipient.

### ISSUE THREAD

**Issue by JPRuehmann** [mganss/EmojiAddIn#41]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Thunderbird 68.6.1 (32Bit)

### Expected behavior
The inserted Emoji show up in the Mail Editor at the desired Position.

### Actual behavior
Only a symbol for a broken Link is shown.

### Steps to reproduce the behavior
Create a new message open the Emoji Add-On Sidebar in the Editor by Clicking on the Icon in the Toolbar put the Cursor into the Body Textarea of the Editor and choose an Emoji.

**Comment by mganss** [comment]
This could be a network connectivity or firewall issue.
1. If you select the broken image, then click the image icon from the editor toolbar and select image from the dropdown to show the properties of the image what is the URL shown?
Should be something like https://cdn.jsdelivr.net/gh/joypixels/emoji-assets@v6.0.0/png/64/1f600.png
2. Also try creating an image in the email and specifying the above URL. Does the image show?
3. One more test would be to save the email (with a broken emoji image) as a draft, then open it in the drafts folder. Does the image show?

**Comment by JPRuehmann** [comment]
1. It shows the Path to the Picture, If I copy that and open the Link in the Browser I get the image.
In the Preview two Icons are shown, The Broken Link Icon and the wished Icon.
2. Yes but to Large.
3. Yes than it get shown.
4. If I use the Image that I beforehanedly entered wit the Path then by chosing from the List again it works as it should.

But  to get for every image the Path by doubleclicking the broken Link image, copy the Path, paste him as image, delete that and than choose from List again seems a very long Way to me.

As I said the images working fine for the recipient but not in the Editor.

**Comment by mganss** [comment]
Can you attach screenshots of how it looks in the compose window and in the properties window? Also, please try and open the debug console using <kbd>Ctrl+Shift+J</kbd> and look for any error messages when you insert an emoji (empty console using the trash icon at the top left before inserting emoji).

**Comment by JPRuehmann** [comment]
Debug: GEThttps://cdn.jsdelivr.net/gh/joypixels/emoji-assets@v6.0.0/png/64/1f1ec-1f1ea.png
Images are at ftp://jpruehmann.dnshome.de/Screenshots/

**Comment by mganss** [comment]
It seems the image doesn't show if you create an image in the email (the large image outline with the broken image indicator). The small flag emoji is the "alternative text" which will probably also show if you make the small broken emoji images inserted through the add-in larger. Can you insert an image into the email using any different URL?

The output in the console is strange, don't know yet where it originates from (perhaps another add-in that interferes?). Please open the developer toolbox using <kbd>Ctrl+Shift+I</kbd> and select the "Network" tab, then try inserting an emoji through the add-in. This should add a line with the request information for the image to the network tab of the developer toolbox (Host should be "cdn.jsdelivr.net", Initiator should be "emoji.js"). Click on this line and attach a screenshot of what it shows. Please also then click on the "Response" tab on the right hand side (other tabs are "Headers", "Cookies", "Request" etc) and attach a screenshot.

You can attach the screenshots directly to this issue by dragging the files to the comment textarea.

**Comment by JPRuehmann** [comment]
Adding a normal image works fine.
Addin images directly in Github is not working for me, Error: something has gone wrong.
Developer Tools says:
Blocked by uBlock0@raymondhill.net
I had whitelisted cdn.jsdelivr.net, will check this again.
Thanks,
