### ISSUE TITLE
Please add favorites / recents at the top

### ISSUE THREAD

**Issue by jikamens** [mganss/EmojiAddIn#46]
Please add support for either marking certain emoji as favorites, or automatically tracking recently used emoji, and putting favorites / recents at the top of the emoji pane.

**Comment by mganss** [comment]
There is the Recent tab already. The display could be changed to display all emoji on a single page and scrolling to specific categories (including Recent) when clicking the category icons (like in current versions of WhatsApp desktop).

**Comment by jikamens** [comment]
D'oh. Didn't realize there was a recents tab. That's exactly what I was looking for! Thank you.
