### ISSUE TITLE
Shortcut to open/close the side bar

### ISSUE THREAD

**Issue by fillods** [mganss/EmojiAddIn#48]
I do like the EmojiAddIn, thank you a lot!  It's running here version 1.78.7 under Thunderbird 78.8.1.

I'm wondering whether there is a keyboard shortcut to open/close the emoji task pane / side bar ?

I had a look at https://support.mozilla.org/en-US/kb/keyboard-shortcuts, but unfortunately the general purpose add-on "Dorando Keyconfig" is not compatible with recent version of Thunderbird.

As a broader goal, I'd love to have a keyboard input method to enter emojis (at least most common's) in mails without having to use the mouse, for the sake of rapidity.

**Comment by mganss** [comment]
Currently, there exists no explicit keyboard shortcut. But you can reach the menu entry by typing <kbd>Alt+V, E</kbd>. In languages other than English replace V with the corresponding letter for the View menu, e.g. in German this would be <kbd>Alt+A, E</kbd>.

**Comment by fillods** [comment]
Thanks, that'll do the trick :-)
So this is <kbd>Alt+A, E</kbd> in French, _wie auf Deutsch_ :wink:

Let's hope there will be one day a keyboard input method to enter emojis, maybe based on keywords inspired by http://www.emoji-cheat-sheet.com ?
