### ISSUE TITLE
Make it work in Thunderbird version 91 (beta in July 2021, next ESR in August 2021)

### ISSUE THREAD

**Issue by Betterbird** [mganss/EmojiAddIn#49]
It doesn't appear to be working in TB 91. Looks like some of the errors come from the WindowsListener. Perhaps @jobisoft has an update.
```
Array.from(...).find(...).xulBrowser.contentWindow is null implementation.js:494
    _loadIntoWindow jar:file:///P:/MAIL-THUNDERBIRD/extensions/emoji@ganss.org.xpi!/api/WindowListener/implementation.js:494
    onLoadWindow jar:file:///P:/MAIL-THUNDERBIRD/extensions/emoji@ganss.org.xpi!/api/WindowListener/implementation.js:334
    checkAndRunExtensionCode resource:///modules/ExtensionSupport.jsm:220
    _checkAndRunMatchingExtensions resource:///modules/ExtensionSupport.jsm:195
    _addToListAndNotify resource:///modules/ExtensionSupport.jsm:179
    _waitForLoad resource:///modules/ExtensionSupport.jsm:156
```

**Comment by jobisoft** [comment]
There is a new version avail:
https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis/WindowListener

**Comment by odtproject** [comment]
I tried installing the latest version of the Add-on (1.78.7) and it doesn't seem to work. I have no idea how to use the Window Listener fix and I don't know that that is even my problem. I'm just an ordinary Thunderbird user. How do I figure out why I'm not seeing the Emoji button in my compose window. I have been using this for a long time, but it disappeared when I updated to TB 91.0. Sure would like to have it back.

**Comment by Betterbird** [comment]
The add-on author needs to make the add-on compatible with TB 91.

**Comment by mganss** [comment]
And I'll attempt to do so shortly 😄

**Comment by Betterbird** [comment]
Don't hesitate to reach out if you run into a problem ;-) @jobisoft can surely answer questions wrt. WindowListener and I'll do my best to help with anything else.

**Comment by mganss** [comment]
@Betterbird Thanks, This one went pretty smoothly, though. Updating WindowListener was enough, mostly.

**Comment by jobisoft** [comment]
I think this can be closed, I had this on my review desk and the updated version is now available on [addons.thunderbird.net](https://addons.thunderbird.net/addon/emojiaddin/versions/).

If you encounter errors while trying out the new version, make sure you have checked all of these:
https://developer.thunderbird.net/add-ons/updating/tb91/changes

**Comment by Betterbird** [comment]
Works for me, thanks!

**Comment by odtproject** [comment]
It works for me too! Thanks!
