### ISSUE TITLE
Emoji Size Changes

### ISSUE THREAD

**Issue by koalayummiez** [mganss/EmojiAddIn#5]
Hello:

I'm not sure if this qualifies as an issue or not, but I wanted to ask you about it anyway to see if you might have some idea about how to fix it.

When I insert emojis in my emails, I see them as the correct size and they're still displayed as the correct size in my sent items. However, when someone receives my email, the emoji looks HUGE.

This is what I see in my sent items:
> ![image](https://cloud.githubusercontent.com/assets/28767142/26178977/af223e20-3b15-11e7-92d1-ae51d0b7d616.png)

This is what the email looks like on the other person's screen:
> ![image](https://cloud.githubusercontent.com/assets/28767142/26178945/804f432c-3b15-11e7-83cf-f86dd93b3cf1.png)

Is there a way to change the code on my end to force the formatting at a certain image size? I love your add-on, but I hope that there's a way to not look like I'm shouting emojis at people. 

Any advice you could give would be appreciated.

Thank you!

**Comment by mganss** [comment]
Which email client and version does the recipient use?

**Comment by mganss** [comment]
No feedback, closing.

**Comment by Drgz001** [comment]
Hi,
I don't know if a closed issue can be reopened but I have this problem, exactly.
I write my massages with TB 68.12.1 and when I read them with Outlook 16.0.13328.20262 64 bits
Thanks

**Comment by mganss** [comment]
@Drgz001 Can you send/forward an example mail to mganss at ustr.onmicrosoft.com?

**Comment by Drgz001** [comment]
Sure !
Thx for the reply

**Comment by Drgz001** [comment]
Done!

**Comment by mganss** [comment]
Thanks. I can repro now. This has got to do with missing CSS standards support in Outlook desktop. I'll add a workaround shortly.

**Comment by Drgz001** [comment]
Great news!

**Comment by mganss** [comment]
Fixed in 1.78.6, currently under review at Mozilla, should be up shortly.
