### ISSUE TITLE
Please make it work for TB 102 beta, the future ESR version

### ISSUE THREAD

**Issue by Betterbird** [mganss/EmojiAddIn#52]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)

Thunderbird 102

Doesn't work any more. I took a brief look, document.getElementById("content-frame"); doesn't work any more, that was renamed:
https://hg.mozilla.org/comm-central/rev/66290e800b5c

There might be other issues.

**Comment by jobisoft** [comment]
I tried to get it working: https://github.com/mganss/EmojiAddIn/pull/53
It still needs some work, but if @mganss has a bit of time we sure can get this running.
