### ISSUE TITLE
Emoji side panel doesn't show - get a pop-up instead

### ISSUE THREAD

**Issue by MrYossu** [mganss/EmojiAddIn#59]
Thunderbird 102.0.2 running on Windows 10 64-bit, Emoji 1.102.9

### Expected behaviour
I expected to see the emojis in a side panel, like you see in this image (taken from [this page](https://github.com/mganss/EmojiAddIn))...

![Emoji side panel](https://github.com/mganss/EmojiAddIn/raw/master/Images/thunderbird.png)

### Actual behaviour
I don't have the side panel, and when I click the Emoji button, I get a pop-up window that closes after I click on an icon.

Is there a way to have the side panel always visible like in that screenshot?

Thanks

**Comment by GTR8000** [comment]
Very disappointing, the side panel was incredibly useful! Just like they killed off so many great extensions in Firefox, I see TB is no exception now also. Thank you for continuing to maintain this extension, I'm not directly my frustration towards you!

**Comment by tuxor1337** [comment]
@MrYossu @GTR8000 Please consider filing a bug upstream (i.e. at the official Thunderbird bug tracker): https://bugzilla.mozilla.org/ There is a feature in Firefox for addons to add a sidebar, so there is a certain hope that this feature might also come to Thunderbird at some point.
