### ISSUE TITLE
Should be button on formatting bar, not composition toolbar

### ISSUE THREAD

**Issue by jikamens** [mganss/EmojiAddIn#6]
It would seem to make more sense, and I certainly would find it much more intuitive and convenient, for the button to open the sidebar to be on the formatting bar rather than on the composition toolbar.

**Comment by mganss** [comment]
Sorry for the late response. I don't think this is possible, because for Outlook the only valid `id` for the `OfficeTab` element is `TabDefault`: https://dev.office.com/reference/add-ins/manifest/officetab

**Comment by jikamens** [comment]
Um, I'm talking about Thunderbird, not Outlook?

**Comment by mganss** [comment]
OK, now I get it 😄 The formatting toolbar is only visible when you are composing an HTML mail, though.
