### ISSUE TITLE
no emoji button in Thunderbird 102.2.2

### ISSUE THREAD

**Issue by nbi1** [mganss/EmojiAddIn#62]
Addon is installed and enabled - no emoji button. Worked fine in previous version of Thunderbird.

**Comment by mganss** [comment]
Try to customize the toolbar of the compose window: https://support.mozilla.org/en-US/kb/how-customize-toolbars

**Comment by nbi1** [comment]
Thank you - that did it. Did the list of emoji get smaller? I didn't do a thorough comparison of the last version vs the new, it just looks shorter. Maybe it's a visual effect stemming from how it's presented. Thanks again for the great work.

**Comment by mganss** [comment]
Thanks. No, the number of emoji is the same. Perhaps you had the sidebar at a smaller width than the popup is now?
