### ISSUE TITLE
No Emoji add on in Thunderbird 102.5

### ISSUE THREAD

**Issue by humbugfoto** [mganss/EmojiAddIn#67]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
Thunderbird 102.5.1
### Expected behavior
Emoji add on installed and working
### Actual behavior
Won't install
### Steps to reproduce the behavior
When I download the Emoji add on from it's page, and then click on it to install I get this message:
![Screenshot 2022-11-18 09 54 31](https://user-images.githubusercontent.com/118560892/202772493-222936a0-fbc0-4a03-99bd-a6bd0d5cc7ff.png)

I have downloaded the add on several times, I have uninstalled and reinstalled Thunderbird twice and I still get the same message: "add on could not be installed because it has not been verified".

I've been using the Emoji add on for years, and this is the first time something like this has happened, only now with the Tbird upgrade to v.102.4 and 102.5

**Comment by mganss** [comment]
I believe what's happening is that Firefox tries to install the add-on into the browser (FF and TB addons use the same format). Please try installing from within TB as described here: https://support.mozilla.org/en-US/kb/installing-addon-thunderbird

**Comment by humbugfoto** [comment]
Thank you. That seems to have fixed the problem.
