### ISSUE TITLE
Focus should switch back to editor after inserting emoji

### ISSUE THREAD

**Issue by jikamens** [mganss/EmojiAddIn#7]
After I click on an emoji to insert it, focus should switch back to the editor window rather than remaining in the sidebar.

**Comment by mganss** [comment]
Good suggestion. I've got this working in Thunderbird but can't test in Outlook currently because of serverside problems in Office 365 🙄 Hopefully tomorrow...

**Comment by mganss** [comment]
Works in Outlook Web, too. In Outlook Desktop it works but only after the sidebar has had focus once, i.e. from the second click on.

In Thunderbird it's in 1.5.2 which is currently being  reviewed by Mozilla, should be live in a day or two, possibly even a few hours.
