### ISSUE TITLE
Floating toolbar vs. fixed always visible

### ISSUE THREAD

**Issue by BlueWings76** [mganss/EmojiAddIn#72]
### Application and version where the issue occurs (e.g. Thunderbird 52.0, Outlook Desktop 2016, Outlook Web)
ThunderBird 102.12.0 (64-bit)
Emoji 1.102.10

### Expected behavior
Emoji pick-up list is docked inside right edge of composition window, it is always visible. Like here : 
https://www.updatestar.com/dl/emoji/emoji.html

### Actual behavior
Emoji pick-up list opens up only when I click the Emoji button on toolbar, and disappears after selecting any item.

### Steps to reproduce the behavior
Install ThunderBird, then install Emoji.

I'd like the Emoji button on toolbar to behave like it's used to, toggling the pick-up list on and off.

Thanks, Peter

![Emoji bad](https://github.com/mganss/EmojiAddIn/assets/78958196/dc5a7c2b-8dc8-409d-a1ac-b0c94033703f)
![Emoji good](https://github.com/mganss/EmojiAddIn/assets/78958196/605efac6-8c48-4cee-9413-2b149b1d85fb)

**Comment by mganss** [comment]
The docked panel is no longer possible in TB 102. See discussion at #53.
