### ISSUE TITLE
AddIn for OWA?

### ISSUE THREAD

**Issue by Commifreak** [mganss/EmojiAddIn#8]
Is there a way to add this AddIn to an Outlook Web Access?

I use OWA with an Exchange 15.0.1263.5.

**Comment by Commifreak** [comment]
Ah, Got it. Simply convert xml and made some adaptations and some renames.

If someone wants this as OWA plugin, Open App overview, select add via URL and type in: https://kluthr.de/owa_emojis/EmojiAddin.xml

Thanks :)

**Comment by Commifreak** [comment]
Hint: Images folder should be lowercase (images) as defined in your xml.

**Comment by Commifreak** [comment]
And: the url to the css file is wrong in TaskPane.html. link goes to .css but the filename is .scss (TaskPane.scss).

**Comment by mganss** [comment]
No: TaskPane.scss is the unpreprocessed [Sass](http://sass-lang.com/) file, TaskPane.css is the compiled CSS file (only this can be properly used by a web browser).

**Comment by fidergo-stephane-gourichon** [comment]
> If someone wants this as OWA plugin, Open App overview, select add via URL and type in: https://kluthr.de/owa_emojis/EmojiAddin.xml

Just to mention that URL now returns 404.

**Comment by Commifreak** [comment]
Correct, sorry but I deleted that. Its easy to host this on your own with some path adjustments.

Gruß,
R. Kluth
